[project]
name = "yt2cli"
version = "0.2.2"
description = "Access To Youtube Easly From Your Terminal Without Api Key"
authors = [
    {name = "Ahmed Hassan",email = "ah8438263@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "yt-dlp (>=2026.7.4,<2027.0.0)",
    "term-image (>=0.7.2,<0.8.0)",
]

[project.scripts]
yt2cli = "yt2cli.cli:main"

[tool.poetry]
packages = [{include = "yt2cli", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
