[project]
name = "yt2cli"
version = "1.0.0" # Im Using That on Local to run Poetry
dynamic = ["version"]
description = "Access To Youtube Easily From Your Terminal"
authors = [
    {name = "Ahmed Hassan",email = "ah8438263@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "yt-dlp (>=2026.7.4,<2027.0.0)",
    "term-image (>=0.7.2,<0.8.0)",
    "pyperclip (>=1.11.0,<2.0.0)",
]

[project.scripts]
yt2cli = "yt2cli.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"
[tool.setuptools_scm]
